### ISSUE TITLE
How to add users?

### ISSUE THREAD

**Issue by peteruithoven** [rikva/voko#10]
How should users be added?
When I use `/admin/accounts/vokouser/add/` I always get a `Herstel de fouten hieronder.`  error, sometimes without specific errors shown below. Even when I fill in all fields. 

The page also mentions:
> Vul allereerst een gebruikersnaam en wachtwoord in. Vervolgens kunt u de andere opties instellen.

Which are two fields I don't see in this form.

**Comment by rikva** [comment]
Oops. It's best to follow the end-user flow. Let me explain:

* I've just pushed a change to master that disables the CAPTCHA in local development. It would not work locally without a token. Best to rebase/merge it.

1. Register using http://localhost:8000/accounts/register/thanks/
1. In local development, the email being sent is stored in `/tmp/app-messages`. Visit the link on your local webserver (e.g. http://localhost:8000/accounts/register/confirm/TOKEN)
1. Log in as superuser and go to user admin (http://localhost:8000/admin/accounts/vokouser/)
1. Select your user, choose in dropdown: "Gebruikersactivatie na bezoek info-avond", click button
1. "Can activate" boolean will show as True
1. Log out as superuser, or visit the next link in incognito.
1. Edit the registration link from before and replace `register` with `finish` (e.g. http://localhost:8000/accounts/register/finish/TOKEN).

I realize this is kind of a hassle... being the only developer I never prioritized making this any simpler.

**Comment by peteruithoven** [comment]
Thanks for the quick answer. I'll try writing something in the Readme. 

I'm stuck at step 2, I have one message in `/tmp/app-messages`, but it doesn't seem to contain a token.
```
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: VOKO Utrecht - 
From: VOKO Utrecht <info@vokoutrecht.nl>
To: Bob Uithoven <peteruithoven@gmail.com>
Date: Wed, 20 Feb 2019 12:33:00 -0000
Message-ID: <20190220123300.28530.82002@xps>



-------------------------------------------------------------------------------
```

Could it be that I need to add a mail template that includes the token? I see it's possible to add mail templates in the admin section.
