### ISSUE TITLE
Correcties overzicht verbeteren

### ISSUE THREAD

**Issue by peteruithoven** [rikva/voko#109]
Een eerste stap naar #106 is om het correcties overzicht te verbeteren. 

Correctie pagina voor bestelronde #141: 
https://leden.vokoutrecht.nl/ordering/admin/round/141/correction/

Verzoek:
> Op zich is het al handig dat de pagina met correcties een overzicht geeft van alle correcties, maar wat ik er nog niet zo handig aan vind (voor het versturen van de mails althans) is dat de correcties niet worden gegroepeerd per boer en ook niet per product. Dus in het voorbeeld dat jij stuurt staat bijvoorbeeld Walnoten verspreid over de lijst. Het zien van namen van leden waarbij de correcties zijn doorgevoerd is handig voor tijdens het invoeren van correcties maar maakt voor het sturen van de mails dan weer niets uit. Dus eigenlijk zou ik dan een overzicht willen waar zou staan 
> 
> Nieuw Slagmaat:
> 21x Walnoten 
> 
> Geertjes Hoeve:
> 3x Chevron worstjes
> 
> Food4Good:
> 4x Winterpostelein (of dan zou het misschien 65% van 6x Winterpostelein zijn)
> 
> Ik besef me nu bij het maken van bovenstaande lijst dat we dus soms ook minder geleverd krijgen en dat leden een percentage van de bestelling krijgen en dus een deel van hun geld terug, maar dat niet altijd in de beschrijving staat hoeveel gram/kilo een portie is, dus dat dat voor jou moeilijk te programmeren is. 
> 
> Leverancier belasten staat erin omdat het ook kan dat we bij uitdeel iets kapot maken/laten vallen en dan vergoedt VOKO het zelf en wordt de boer niet belast. Maar dat heb ik nog nooit meegemaakt. 

Voorbeeld van een email:
> ## Subject: VOKO ronde 141
> Beste [contact persoon Geertjes hoeve],
> 
> De volgende producten zijn afgelopen ronde niet geleverd:
> 
> - 5x eieren 10 stuks
> - Chevron worstjes
> - Chevron saucijsjes
> 
> Klopt dit met jouw administratie?
> 
> vriendelijke groeten,
> Florentine

Relevante template: https://github.com/rikva/voko/blob/master/webapp/templates/ordering/admin/correction.html
Relevante view: https://github.com/rikva/voko/blob/26ce27e38eab5431a85f45d2bd485f1d24ce0789/webapp/ordering/admin_views.py#L170-L211

**Comment by peteruithoven** [comment]
Het plan is nu om de correcties op te splitsen per leverancier en per leverancier een tabel te maken. Bij de product name kunnen we dan de leverancier naam weglaten.
De "Leverancier belasten?" kolom kan weg als we een losse tabel op het einde toevoegen voor correcties waarvoor de VOKO wordt belast. 

Nu is de vraag nog of we meer kolommen kunnen weglaten, zoals "lid", "Bestelling" en "Compensatie", daarvoor ga ik contact opnemen met admin teams.

**Comment by peteruithoven** [comment]
Ik heb wat feedback van Anita uit het financiële team gehad. 

> Ik denk dat het wel handig is om deze kolommen te houden. Als er een product niet geleverd is wordt dat inderdaad op productniveau aangegeven maar soms is het zo dat iemand mailt met een klacht/vraag/iets specifieks wat alleen voor die persoon geldt. Dan is het handig om op persoonsniveau iets te kunnen corrigeren voor bijvoorbeeld 1 product. Dat gebeurd niet zo heel vaak maar het lijkt me zonde om de functie eruit te slopen.

Het nadeel van het per lid tonen van correcties is alleen dat dit betekend dat het uitdeel team nog steeds bestellingen handmatig zou moeten optellen. Mijn voorstel zou daarom zijn om alle correcties van een bepaald product wel bij elkaar op te tellen, maar dan daaronder (in een soort sub gedeelte) alsnog de correcties per lid op te nemen. In dit sub gedeelte zouden dan alle lid correctie specifieke info moeten komen, zoals de naam va het lid, de bestelling en hun compensatie. 

Als ik het goed begrijp blijven dan over in de per boer tabellen:
- Product
- Besteld
- Geleverd

En per product, in een sub tabel:
- lid
- bestelling
- compensatie. 

Een voorbeeld van een tabel met sub gedeeltes zijn de bestelling overzichten die we tonen op de transport rit info pagina's:
![Screenshot from 2020-04-26 14-10-48@2x](https://user-images.githubusercontent.com/523210/80307274-48a1e580-87c8-11ea-816d-72050c1defb6.png)
Template: https://github.com/rikva/voko/blob/master/webapp/templates/transport/ride.html

Omdat het duidelijk is dat de informatie per lid veel minder gebruikt wordt zouden we deze zelfs "weg kunnen klappen", maar laten we dit alleen doen als dit het technisch redelijk te doen is en het gebruiksvriendelijk blijft. 
Voor een voorbeeld zie op de volgende pagina het Expandable Rows voorbeeld.
https://uxdesign.cc/design-better-data-tables-4ecc99d23356#9369
De datatable library die we gebruiken voor complexere tabellen heeft een row details functie die we misschien kunnen gebruiken, al maakt dat dingen misschien te complex. 
https://datatables.net/examples/server_side/row_details
Een optie met bootstrap zelf met wat javascript: 
https://stackoverflow.com/a/16864694/1544200
Al zou ik wel altijd een soort pijl icoontje toevoegen om deze functionaliteit duidelijk te maken.

**Comment by mgvd** [comment]
Is dit wat je bedoelt? Dit is nog zonder de wens om de regels voor leden in te kunnen klappen:

![image](https://user-images.githubusercontent.com/2269746/80476654-f6d59880-894a-11ea-82dd-bfdc648f252b.png)

**Comment by peteruithoven** [comment]
Yes precies. 
Ben wel benieuwd waarom je ervoor gekozen hebt de namen van de boeren nu in de tabel te verwerken ipv zoals voorheen als losse headers?

Ik zal die afbeelding ook nog even naar Florentine en Anita sturen, zodat ze een beeld hebben van waar we naar toe werken.

**Comment by peteruithoven** [comment]
Feedback van Anita: 

> Oja, duidelijk zo ja. Ik ben sowieso echt onder de indruk van alle veranderingen die jullie doorvoeren en hoe snel jullie alles doen. Lekker bezig!

**Comment by mgvd** [comment]
Goed, dan zal ik het op deze manier afmaken. De naam van boeren heb ik onderdeel gemaakt van  header, omdat mij dat netter leek.

**Comment by mgvd** [comment]
Zijn er nog meer dingen die we hierbij willen implementeren, of kan dit issue worden gesloten?

**Comment by peteruithoven** [comment]
Wat we blijkbaar nog zijn vergeten is het los benoemen van correcties waarvoor de VOKO zelf belast wordt. (Zie email) We hebben nu alleen de kolom die dat aangeeft weggelaten. 

Wat ik zou voorstellen is dat we bij de leveranciers alleen de correcties tonen waarvoor ze belast worden en dan onderaan een lijst toevoegen onder iets als "VOKO belast". In die lijst zou het dan waarschijnlijk wel goed zijn om de leverancier naam weer bij de product naam te zetten.

**Comment by peteruithoven** [comment]
Volgens mij zijn met https://github.com/rikva/voko/pull/117 dit helemaal voltooid. Thanks @mgvd!
