### ISSUE TITLE
Transport scheduling

### ISSUE THREAD

**Issue by peteruithoven** [rikva/voko#12]
Now that all members of the VOKO are expected to help out with Transport it's much more important to send out a informative reminder every 2 weeks. Currently this is done manually by the transport coordinators. 
I'd like us to keep doing this manually, making sure we figure out how this should work, but in the future I'd like to automate this. Some thoughts on how this could be accomplished:
Because we need to send mails to whomever does the Transport that week, we'll need to do the Transport scheduling on leden.vokoutrecht.nl. I was thinking we could make a lists or rides, storing per ride:
- Date or link to order round
- Route: A / B / A+B
- Driver: Link to profile
- Co-driver: Link to profile

We'll need to create a new page for people to view the schedule. This is might be difficult if people haven't allowed sharing their contact information and if that means we can't show people's names. 
**Update:** To limit contact information sharing we could only show members their rides and the contact information of the members relevant for those rides. 

We need a way for Transport coordinators to edit the schedule. Not sure if we can/should use the /admin page for that. 
**Update:** We'll try using the admin first. 

We'll need to make sure Transport coordinators have schedule edit rights. 

With this we should have enough information to, after the order round is closed automatically send out an email to all drivers and co-drivers of that round with information like: 
- Some basics,
- Link to transport manual (http://vokoutrecht.nl/transport/)
- Contact information of drivers and co-drivers. I'm not sure if we can do this if people haven't allowed sharing their contact information. 
- Contact information of relevant coordinators. 
- Link to order lists of round
- I'm not sure how members should get access to contact information of our farmers / suppliers. See: #13. Currently we've shared a link to a google spreadsheet on https://leden.vokoutrecht.nl/docs/)

Open questions:
1. How should members get access to contact information of our farmers / suppliers? See: #13. Currently we've shared a link to a google spreadsheet on https://leden.vokoutrecht.nl/docs/)
2. What can we include in the emails if members didn't allow sharing their contact information?
3. Can we include names in the schedule if members didn't allow sharing their contact information?
4. Can we use the /admin pages for schedule editing or do we need to create pages for that?

**Comment by rikva** [comment]
> * How should members get access to contact information of our farmers / suppliers? See: #13. Currently we've shared a link to a google spreadsheet on https://leden.vokoutrecht.nl/docs/)

That information is already publicly available, isn't it? 

> * What can we include in the emails if members didn't allow sharing their contact information?

Not a lot, I'm afraid. 
I'm thinking if simply matching two people together (instead of exposing a list of everybody's names and/or contact info) is less of a problem, GDPR-wise.

> * Can we include names in the schedule if members didn't allow sharing their contact information?

Currently everybody's names is shared in a big google spreadsheet. This is most likely in violation of GDPR as well. 
However, I don't really see a way around this, except for
- obfuscating names ("Peter U." / "Rik v." )  -- not sure what the law says about this
- only showing the names of members the logged-in member is scheduled for transport with  

> * Can we use the /admin pages for schedule editing or do we need to create pages for that?

Those admin views *can* be pretty flexible but they have their limits. We could start out with using the built-in admin and write custom admin pages if needed.

**Comment by peteruithoven** [comment]
>> * How should members get access to contact information of our farmers / suppliers? See: #13. Currently we've shared a link to a google spreadsheet on https://leden.vokoutrecht.nl/docs/)

> That information is already publicly available, isn't it?

No? I can't imagine every contact person has publicly listed their phone number for example? 
Some limited information is shared on our public website, see: https://vokoutrecht.nl/boerenwiki/
The spreadsheet is publicly available, but only if you know the link, which is a bit risky.

> > * What can we include in the emails if members didn't allow sharing their contact information?

> Not a lot, I'm afraid.
> I'm thinking if simply matching two people together (instead of exposing a list of everybody's names and/or contact info) is less of a problem, GDPR-wise.

That only covers reminders though, people need to be aware of the schedule in advanced. If we can't show the list on the leden.vokoutrecht.nl website we'll need to figure out another way to inform members. 
Maybe a personal mail when a member is scheduled, with only the information that's relevant for them?

**Comment by rikva** [comment]
I think sharing the suppliers info is not that big of a problem. We can probably come up with some way that shows supplier info only to relevant members, scheduled for transport shifts in the (near) future.

I'm a bit concerned about sharing info between members, and I feel like I'm not authorized or familiar enough with GDPR / privacy law to make any decisions on this. 

We do have a Privacy Statement (https://leden.vokoutrecht.nl/privacy/) (I co-authored it) that all our members agreed with. It might be possible that under this statement we can safely share info between members, but I'm just not sure.

**Comment by peteruithoven** [comment]
The GDPR should allow using this information as long as we describe that we use it and why. 
In our case Transport coordination is very very hard when we can't share contact information on a limited basis.
We should also limit usage where possible.
