### ISSUE TITLE
Bij correcties geleverd percentage ontbreekt 30%

### ISSUE THREAD

**Issue by peteruithoven** [rikva/voko#123]
Florentine: 
> Ik zag bij het invoeren van correcties dat 30% ontbreekt in de lijst met geleverd percentage, en dat 20% er twee keer instaat. Kunnen jullie dit aanpassen?

![Screenshot 2020-07-14 at 19 40 56](https://user-images.githubusercontent.com/523210/87465135-743cab00-c614-11ea-87ad-490436536e50.png)

I don't really get why this is a dropdown / select at all. Some number input field seems more appropriate, but will require more validation.

**Comment by rikva** [comment]
Ik denk dat het een dropdown is om het veld sneller te kunnen doorlopen. Maar er zit blijkbaar al jaren een copy/paste fout in. Een invoerveld is ook prima, zoals je zegt moet er meer validatie plaatsvinden.
