### ISSUE TITLE
update automatische prepare mail 

### ISSUE THREAD

**Issue by mgvd** [rikva/voko#126]
We willen de automatische prepare mail een klein beetje aanpassen (corona en een tussenkopje toevoegen). Zie hieronder de aangepaste versie. Omdat we nu met twee coördinatoren zijn, willen we ook graag automatisch de goede coördinator invullen (in het rood hieronder)

Beste {{ user.first_name }},

Over twee weken sta je ingeroosterd voor transport. Dit betekent dat er alvast wat dingen moeten worden voorbereid. Als bijrijder kun je aankomende woensdag de sleutel van Averechts komen ophalen bij de uitdeelavond. Als chauffeur is het belangrijk ervoor te zorgen dat je over twee weken op woensdagmiddag een auto tot je beschikking hebt.

Corona
VOKO gaat ook in deze tijd gewoon door. Spreek als chauffeur en bijrijder af of je het ziet zitten om samen in de auto te zitten of dat je liever alleen rijdt. Dan zou de bijrijder bijvoorbeeld kunnen helpen met laden en lossen.

Belangrijke informatie
Alle informatie en contactgegevens voor deze rit vind je op: {{ base_url }}{% url 'ride' ride.slug %}
Algemene informatie vind je op: https://vokoutrecht.nl/transport/
General information in English can be found here: https://vokoutrecht.nl/transport-tasks/

Als je nog vragen hebt, kun je contact opnemen met de _transportcoördinator_. Bedankt voor het helpen met transport!

Groene groetjes,
VOKO Utrecht

**Comment by rikva** [comment]
Dat is gewoon een template toch, dus die kan aangepast worden in de Django admin, of niet?

**Comment by mgvd** [comment]
Klopt, dat is opgelost in het template;
