### ISSUE TITLE
Include internal supplier information

### ISSUE THREAD

**Issue by peteruithoven** [rikva/voko#13]
Beside the Transport schedule the other piece of information that's currently shared using a Google spreadsheet (see link on https://leden.vokoutrecht.nl/docs/) is supplier information. Things like: 
- Name
- Name contact person (sensitive)
- Phone number(s) (sensitive)
- Email (sensitive)
- Address
- Advice on how many crates to bring and whether to bring cooler
- Extra information (sensitive)

Currently suppliers are already included in leden.vokoutrecht.nl, but we'll need to add extra fields:
- Name contact person
- Phone number(s)
- Free form transport information field (I think advice on how many crates to bring etc could also be included in this) 

We'll need a way for members to access this information, probably a new page.

If we have this information it could even be added automatically in the reminders (see #12).

**Comment by rikva** [comment]
Regarding sensitive supplier information, I would assume that we can expose this information to the scheduled transport teams per order round, this would be pretty much what the suppliers consent with, right?

**Comment by peteruithoven** [comment]
@rikva you wouldn't make this permanently accessible for members on a page but limit this to scheduled transport teams? For example by only including the information in the reminder mail?

**Comment by rikva** [comment]
I think that is an option, yes, but I'm just thinking out loud here... We could also expose the info on a view, but restricted to active transport teams.
