### ISSUE TITLE
Mobile friendly ordering page

### ISSUE THREAD

**Issue by peteruithoven** [rikva/voko#14]
Currently the [ordering page](https://leden.vokoutrecht.nl/ordering/products/) is build using a big table. This makes it basically impossible to properly scale on smaller devices like mobile phones. I don't think we should simply hide columns. 

The only solution I see is rewriting this screen into something where we can layout the information differently. Maybe something like:
<img width="395" alt="voko order row 2x" src="https://user-images.githubusercontent.com/523210/53182741-68ed7780-35fa-11e9-803b-d383d062eabc.png">

We could try doing this with the current [DataTable](https://datatables.net/) system, by combining multiple pieces of information in one column. We could move the description behind a open button, like shown on: https://datatables.net/. 
Otherwise we'll need to re-implement a lot of things like filters on category and pagination we got for free by using the existing [DataTable plugin](https://datatables.net/).

**Comment by rikva** [comment]
I'm open to improvements, the current site admittedly is largely unsuited for mobile usage.

**Comment by peteruithoven** [comment]
I know :) I hope to find the time. I just wanted to write down all the possible areas of improvement and the ideas I have.
