### ISSUE TITLE
GDPR improvements

### ISSUE THREAD

**Issue by peteruithoven** [rikva/voko#15]
Let's figure out what we need to do to stay inside the GDPR. 
I understand that a large part is describing specifically what information we need and what it is used for. 
Things to improve:
- [x] Include that we use contact information to organize Transport and how we use it. 
- [x] Include that we ask whether members have a drivers license and why we use this.
- [x] Include these free form questions we ask new members?
  > 1. Geef in een top drie aan in welke werkgroepen je voorkeur hebben (1=leukst):
  >   - Administratie
  >   - Contact Boeren
  >   - Techniek (IT)
  >   - Transport (woensdag overdag)
  >   - Uitdeelgroep (woensdagavond)
  > 2. Op welke dagdelen ben je beschikbaar voor VOKO activiteiten?
  > 3. Beschik je over een auto(bus), bakfiets of ander voertuig waarmee producten kunnen worden opgehaald? Heb je talenten die van pas komen binnen VOKO? Of wil je nog iets kwijt?

We might need to be clearer on sleeping members. 
Shouldn't we prevent these users from having access to the members site? 
Shouldn't we remove their data after a while, maybe unless they have a open credit?

So when we clearly explain the goals having a public members list probably isn't an issue. When we implement Transport scheduling #12 we could limit this further, only showing contact information of people involved with the drives you have to make for example. 
We could then also remove the list and make members available though search, this makes it harder for people to copy the complete list.

**Comment by rikva** [comment]
>We might need to be clearer on sleeping members.
>Shouldn't we prevent these users from having access to the members site?

I think that's currently the case.

>Shouldn't we remove their data after a while, maybe unless they have a open credit?

That's an existing process, the admin team actually anonymizes user data after a certain time of inactivity (and with consent of the user).
