### ISSUE TITLE
Email transport reminders

### ISSUE THREAD

**Issue by peteruithoven** [rikva/voko#20]
- [x] Email reminder to drivers and codrivers when order round is closed (PR: #33)
- [x] Email earlier reminder. Maybe before the preceding route reminding them to pick up key? (PR: #41)

These mails should include ride information and or link to the online ride page.

Update: we should send these from rooster@vokoutrecht.nl

**Comment by peteruithoven** [comment]
@rikva I understand that the contents of the emails are stored in the database. Could you share the contents of for example the "Order reminder mail" (id: 4)?

I understand that the reference to these templates, their id's is automatically generated. What's the next `id` going to be?

**Comment by rikva** [comment]
> @rikva I understand that the contents of the emails are stored in the database. Could you share the contents of for example the "Order reminder mail" (id: 4)?

Correct, this is pretty sloppy: the template IDs are hardcoded. I started using https://github.com/jazzband/django-constance to dynamically store these settings but I never converted all constants.

This is the mail: (yes this is wysiwyg-generated html)
```html
<p>Hoi {{ user.first_name }},</p>
<p>Tot <strong>&nbsp;{{ order_round.closed_for_orders }}</strong><strong>&nbsp;</strong>kun je nog al het lekkers van onze boeren bestellen! Direct even doen? Klik <a href="http://leden.vokoutrecht.nl/ordering/products/">hier</a>.<br /><br /> A.s. woensdag staat het dan tussen 18.00 en<strong>&nbsp;</strong>20.30 uur in caf&eacute; Averechts voor je klaar.&nbsp;<br /><br />Heb je vragen, tips, ben je ergens niet zo blij mee of heb je leuke idee&euml;n? Mail ons! Stuur je berichtje naar boeren@vokoutrecht.nl.<br /><br />Groene groeten!<br />VOKO Utrecht</p>
```

> 
> I understand that the reference to these templates, their id's is automatically generated. What's the next `id` going to be?

It will be id 84

**Comment by peteruithoven** [comment]
We're sending all the reminders
