### ISSUE TITLE
Add distribution coordinator to Ride

### ISSUE THREAD

**Issue by peteruithoven** [rikva/voko#22]
I've come to understand that the distribution (uitdeel) coordinators of specific rides also need access to contact information of drivers. 

The simplest solution for now is probably to add a distribution coordinator field to Ride.

**Comment by rikva** [comment]
Yes, or to `OrderRound`?

**Comment by peteruithoven** [comment]
> Yes, or to `OrderRound`?

That's a better idea, because there are usually multiple Rides per OrderRound.

**Comment by peteruithoven** [comment]
Later on we might get something like a Distribution type that links to a OrderRound (just like Rides) so that we're able to add more distribution specific information.
