### ISSUE TITLE
Sort rides on ride listpage by date, ascending

### ISSUE THREAD

**Issue by rikva** [rikva/voko#45]

**Comment by peteruithoven** [comment]
> Oh, I meant on this page: https://leden.vokoutrecht.nl/transport/schedule/

Could it be that you've customized the sorting on your side? 
For me it is sorted on the date:
![Screenshot from 2019-04-15 20-40-50@2x](https://user-images.githubusercontent.com/523210/56157157-1ce9fe00-5fbf-11e9-8166-598599a4a8db.png)

**Comment by rikva** [comment]
Right, it's customizable, but the default sorting seems random, but I see in the source code that it orders by ID. Which should usually be good but if I test it in an incognito window the ordering is weird?

It's not that big a deal, I just noticed it this morning!

**Comment by peteruithoven** [comment]
Ah when I locally create some order rounds in a weird order it does go wrong.

![Screenshot from 2019-04-15 21-09-56@2x](https://user-images.githubusercontent.com/523210/56158643-e1e9c980-5fc2-11e9-9664-39286b9b32af.png)

When I order the DataTable in javascript using something like
```
.order( [ 0, 'desc' ], [ 1, 'asc' ] ).draw();
```
It also goes wrong:
![Screenshot from 2019-04-15 21-10-36@2x](https://user-images.githubusercontent.com/523210/56158690-080f6980-5fc3-11e9-8697-7479ed729cb5.png)

I guess it doesn't understand the dates, it seems to sort them as regular strings or something.

**Comment by peteruithoven** [comment]
I'm afraid that the easiest solution would be to disable ordering and sort in the view. 

There are ways to do this properly with DataTable though: https://datatables.net/blog/2014-12-18
