### ISSUE TITLE
Uitdeel roostering

### ISSUE THREAD

**Issue by peteruithoven** [rikva/voko#61]
Het zou goed zijn om ook het uitdeelrooster te automatiseren. Dit zou het leven van de coordinatoren makkelijker maken en de coordinator rol daarbij toegankelijker maken. Het kan hopelijk ook helpen om het uitdeel team van betere informatie te voorzien en de ervaring consistenter te maken. 

Ik ben niet goed op de hoogte van hoe het uitdeel team werkt, maar ik kan me voorstellen dat we zoiets nodig hebben:
- Per bestel ronde zijn er meerdere diensten (shifts)
- Per dienst moeten er 1 of meer leden ingeroosterd worden. 
- Ingeroosterde leden hebben toegang nodig tot de volgende informatie per ronde:
  - Contact informatie van:
    - Alle leden die die dag zijn ingeroosterd, op alle diensten. Dit maakt mogelijk dat ze met elkaar kunnen communiceren.
    - Uitdeel coordinator
    - ~~Rijder +~~ bijrijder die sleutels moeten ophalen
    - Leveranciers die producten hebben aangeboden (of gaat dit contact via boeren team?) (Florentine: hoogstens voor de uitdeelcoordinator)
  - Informatie van bestellingen of gebruiken ze daarvoor de uitgeprinte informatie? (Florentine: uitgeprinte informatie)
- Ingeroosterde leden krijgen een herinneringen per mail:
  1. ~~Iets van 2 weken voor uitdeel dag?~~
  2. Een paar dagen voor uitdeel dag? (Eva: zondag) (Florentine: maandag)

Leden van het uitdeel team kunnen de dagen inzien dat zij zelf zijn ingeroosterd, de coordinatoren kunnen het hele rooster inzien en bewerken. 

## [ToDo](#todo)
- [x] Data modellen #72
- [x] Views #72
- [x] Links #72
- [x] Volgende bijrijders die sleutels moeten ophalen #72
- [x] Toon informatie van leden van alle shifts voor die ronde #72
- [x] Herinnerings email #72

**Comment by Evabullens** [comment]
Hoi Peter,

dankjewel voor de opzet. Volgens mij is ie al zo ongeveer compleet! 
De reminder stuur ik altijd op zondag voor het uitdelen. Anders vergeet je het weer.

**Comment by peteruithoven** [comment]
@Evabullens bedankt voor de review! Deze vragen staan nog open:
1. Hebben de uitdeel leden toegang nodig tot de contact informatie van de leveranciers die producten hebben aangeboden of gaat dit contact via boeren team?
2. Hebben de uitdeel leden toegang nodig tot de bestel informatie or gebruiken ze daarvoor de uitgeprinte informatie?
3. Denk je dat behalve een reminder op zondag nog een extra reminder nodig is?

**Comment by peteruithoven** [comment]
Florentine:
> 1. Hebben de uitdeel leden toegang nodig tot de contact informatie van de leveranciers die producten hebben aangeboden of gaat dit contact via boeren team?

Wat mij betreft niet, voor de uitdeelcoordinator kan dat wel handig zijn

> 2. Hebben de uitdeel leden toegang nodig tot de bestel informatie or gebruiken ze daarvoor de uitgeprinte informatie?

Uitgeprinte info 

> 3. Denk je dat behalve een reminder op zondag nog een extra reminder nodig is?

Ik denk dat één reminder voldoende is, maar misschien op maandag i.p.v. zondag? 
    Denk je dat behalve een reminder op zondag nog een extra reminder nodig is?

Het zou vooral voor de uitdeelcoordinator handig zijn om info te hebben over rijders + bijrijders die sleutels nodig hebben, en lijkt me dat voor de andere uitdelers geen noodzakelijke informatie. 
Het zou ook voor de uitdeelcoordinator handig zijn om te weten wie de volgende keer uitdeelcoordinator is, i.v.m. uitwisselen sleutel Averechts.

**Comment by peteruithoven** [comment]
Sneak peak:
## Uitdeel rooster overzicht
![Screenshot from 2019-06-25 15-45-03](https://user-images.githubusercontent.com/523210/60103748-72c9e780-9760-11e9-8a27-eb6cf3d98c1e.png)
## Uitdeel dienst
![Screenshot from 2019-06-25 15-45-26](https://user-images.githubusercontent.com/523210/60103774-81180380-9760-11e9-83c3-e5c6964ea496.png)

**Comment by Evabullens** [comment]
Wow! Fantastisch!
Krijg iedereen hier dan ook een mailtje van, net als bij t transport-rooster?
————————
T:  06 4399 2473
W: www.evabullens.org<http://www.evabullens.org>


[cid:5B5F8A9A-8252-42CB-ABF8-60B1BD7AFB37@lan.inderuimte.org]

Op 25 jun. 2019, om 15:48 heeft Peter Uithoven <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Sneak peak:

Uitdeel rooster overzicht

[Screenshot from 2019-06-25 15-45-03]<https://user-images.githubusercontent.com/523210/60103748-72c9e780-9760-11e9-8a27-eb6cf3d98c1e.png>

Uitdeel dienst

[Screenshot from 2019-06-25 15-45-26]<https://user-images.githubusercontent.com/523210/60103774-81180380-9760-11e9-83c3-e5c6964ea496.png>

**Comment by peteruithoven** [comment]
@Evabullens das op het moment de laatste todo ;)

**Comment by Evabullens** [comment]
Super vet, echt fijn!
————————
T:  06 4399 2473
W: www.evabullens.org<http://www.evabullens.org>


[cid:5B5F8A9A-8252-42CB-ABF8-60B1BD7AFB37@lan.inderuimte.org]

Op 25 jun. 2019, om 16:05 heeft Peter Uithoven <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@Evabullens<https://github.com/Evabullens> das op het moment de laatste todo ;)

**Comment by rikva** [comment]
@peteruithoven Ik heb gezien waar je mee bezig bent, ik probeer deze week naar je PRs te kijken, en naar de kapotte CI.

**Comment by peteruithoven** [comment]
We hebben alles inmiddels geïmplementeerd dus ik sluit deze issue.
