### ISSUE TITLE
Nieuwe leden indelen versimpelen?

### ISSUE THREAD

**Issue by peteruithoven** [rikva/voko#63]
De ledenadministratie kijkt na elke bestel ronde wie contributie heeft betaald en gebruikt die lijst om mensen te benaderen over een indeling in een team. Hierbij kijken ze naar de voorkeuren die ze bij het voltooien van hun account hebben ingevuld. 
Kunnen we deze handeling makkelijker maken?

Op het moment gebruiken ze daarvoor bijv. de volgende bestellingen pagina waar ze dan zoeken op "Ledenbijdrage".
https://leden.vokoutrecht.nl/ordering/admin/round/117/user_orders/

Willen we dit perse per bestelronde inzien of kunnen we beter 1 pagina maken met leden die nog niet ingedeeld zijn (mogelijk verdeeld per bestel ronde)?

Mogelijk kunnen we hier een algemenere leden administratie pagina van maken waar ze makkelijk meer informatie kunnen inzien waarvoor ze de ledenlijsten naar excel exporteren?

**Comment by peteruithoven** [comment]
Ik wil een aantal dingen doen:
1. Een "Has payed" kolom toevoegen aan leden administratie pagina.
2. Een "Has payed" filter toevoegen aan leden administratie pagina.

Hiermee kan men een makkelijk overzicht krijgen van alle leden die een bestelling hebben voltooit maar nog niet zijn ingedeelt in een groep. 

3. Een kolom toevoegen aan de [Bestelrondes overzicht pagina](https://leden.vokoutrecht.nl/ordering/admin/rounds/) met per per ronde een lijst van leden die voor het eerst hebben besteld. Deze lijst moet linken naar de persoonlijke informatie van laden zodat men de indeling voorkeuren kan lezen en het lid in een groep kan indelen.

**Comment by paulinehilkens** [comment]
Klinkt goed!

**Comment by peteruithoven** [comment]
Die 3 verbeteringen zijn doorgevoerd dus ik sluit deze af.
