### ISSUE TITLE
Content order round accounts info makes no sense

### ISSUE THREAD

**Issue by peteruithoven** [rikva/voko#84]
Not sure what is going on but something is going wrong with the new order round accounts info. It should list members who, during the specific order round have paid the members pee (which should give us a list of new members).

The current way to retrieve these new members is to search for "Ledenbijdrage bij eerste bestelling" on the user orders page. For example round 121: 
https://leden.vokoutrecht.nl/ordering/admin/round/121/user_orders/
Gives one name, but the matching accounts info lists that user + some other users: 
https://leden.vokoutrecht.nl/ordering/admin/round/121/accounts/

The following examples even list different people, while there where no new members. 
- https://leden.vokoutrecht.nl/ordering/admin/round/122/accounts/ (compare with: [user orders](https://leden.vokoutrecht.nl/ordering/admin/round/122/user_orders/))
- https://leden.vokoutrecht.nl/ordering/admin/round/123/accounts/ (compare with: [user orders](https://leden.vokoutrecht.nl/ordering/admin/round/123/user_orders/))

PR that added this functionality: https://github.com/rikva/voko/pull/79

**Comment by peteruithoven** [comment]
## URL config
``` python
url(r'^round/(?P<pk>[0-9]+)/accounts/$', OrderAccounts.as_view(),
  name="orderadmin_accounts"),
```

## View
``` python
class OrderAccounts(GroupRequiredMixin, DetailView):
    model = OrderRound
    template_name = "ordering/admin/orderround_accounts.html"
    group_required = ('Admin')
```

## Relevant piece of the template
```` python
  {% for order in object.orders.all %}
    <ul class="list-group">
      {% if order.member_fee %}
        <a href="{% url 'admin:accounts_vokouser_change' order.user.id %}"><li class="list-group-item">{{ order.user }}</li></a>
      {% endif %}
    </ul>
  {% endfor %}
```

It's so simple, and the results so random, I'm not sure what is happening.

**Comment by rikva** [comment]
I think the `member_fee` method returns a list of users that *should* pay the member fee in that round **if they order**, but I'd need to look closer at it later.

**Comment by peteruithoven** [comment]
But, I'm specifically going through the orders in the specific order round...

Just to compare with the user orders logic:

## URL config
https://github.com/rikva/voko/blob/5cee46e860bdbf9a23715cc505d6811672561ee4/webapp/ordering/admin_urls.py#L25-L26

## View
https://github.com/rikva/voko/blob/5cee46e860bdbf9a23715cc505d6811672561ee4/webapp/ordering/admin_views.py#L70-L82

## Template
https://github.com/rikva/voko/blob/5cee46e860bdbf9a23715cc505d6811672561ee4/webapp/templates/ordering/admin/user_orders_per_round.html#L16
https://github.com/rikva/voko/blob/5cee46e860bdbf9a23715cc505d6811672561ee4/webapp/templates/ordering/admin/user_orders_per_round.html#L52-L61

**Comment by rikva** [comment]
I think the issue might be in this line:
```object.orders.all```

`Order` basically starts as a "shopping cart". For each user that logs in to the system, per order round, an Order object is created.
That means lots of empty orders, sometimes unfinished orders.

To get all "real" orders you want to filter on `paid=True`. You can't do this from the template you you could either manually put the paid orders in the view context (this is done in a few places) or add a method to OrderRound that you can call from the template (e.g. `paid_orders`).

**Comment by peteruithoven** [comment]
Ah! I did not realize that. I think I'd add it to the model because this might be relevant for more views and that keeps the view simple.
